{% set name = "scip" %}
{% set version = "0.1.11.post4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scip-{{ version }}.tar.gz
  sha256: 0e06e1fe500da82caa427b2cc065e4400ce5cb6c06ae2991ead33c5d3c2ecc5d

build:
  entry_points:
    - scip = scip.main:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pillow
    - dask-core >=2022.01.1
    - click
    - scikit-image
    - pyyaml
    - python-graphviz
    - zarr
    - pyarrow
    - anndata
    - pandas
    - numba
    - aicsimageio
    - dask_mpi
    - mpi4py
    - cellpose
    - aicspylibczi

test:
  imports:
    - scip
  commands:
    - pip check
    - scip --help
  requires:
    - pip

about:
  home: https://github.com/ScalableCytometryImageProcessing/SCIP
  summary: Scalable Cytometry Image Processing (SCIP) is an open-source tool that implements an image
  dev_url: https://github.com/ScalableCytometryImageProcessing/SCIP
  doc_url: https://scalable-cytometry-image-processing.readthedocs.io/en/latest
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaximLippeveld
