{% set name = "scip" %}
{% set version = "0.1.11rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scip-{{ version }}.tar.gz
  sha256: 53891aa53a318e5947476d7c1a9787dbd274b85abca00a83f80892d6a127ff79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pillow
    - dask-core >=2022.01.1
    - dask-ml
    - click
    - scikit-image
    - pyyaml
    - python-graphviz
    - pyarrow
    - umap-learn
    - bokeh
    - zarr
    - fastparquet
    - anndata

test:
  imports:
    - scip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scip/
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaximLippeveld
